"""Add address and phone to orders (nullable)

Revision ID: 6be5410cfb55
Revises: 4a637b9db2ba
Create Date: 2025-12-29 11:47:57.455071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be5410cfb55'
down_revision = '4a637b9db2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_orders')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    op.create_table('_alembic_tmp_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
