"""Add payment_gateway table

Revision ID: bbc604623f82
Revises: 5f1a1399a24d
Create Date: 2025-12-29 15:17:29.803631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc604623f82'
down_revision = '5f1a1399a24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('otp_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_gateway', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_gateway_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_gateway_user_id'), ['user_id'], unique=False)

    op.drop_table('gateway_otps')
    op.drop_table('gateway_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway_otps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['gateway_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_gateway', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_gateway_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_gateway_order_id'))

    op.drop_table('payment_gateway')
    # ### end Alembic commands ###
